name: Build release binaries
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux]
        goarch: ["386", "amd64", "arm", "arm64"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup golang version
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Generate the artifacts
        run: make

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.so'
