---
name: Build release binaries
on:
  release:
    types: [created]

# github-action-publish-binaries needs 'contents:write'
permissions:
  contents: write

jobs:
  releases-matrix:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux]
        goarch: ["386", "amd64", "arm", "arm64"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup golang version
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Install dependencies
        run: sudo apt-get install -y libpam-dev

      - name: Generate the artifacts
        run: |
          make
          mv pam_aad_oidc.so pam_aad_oidc.${{ matrix.goarch }}.so

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.so'
