---
name: Build release binaries
on:
  release:
    types: [created]

# github-action-publish-binaries needs 'contents:write'
permissions:
  contents: write

jobs:
  releases-matrix:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Go build tools
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Update package repositories
        run: sudo apt update

      - name: Setup C++ build tools
        run: sudo apt install -y gcc make

      - name: Install build dependencies
        run: sudo apt install -y libcurl4-openssl-dev libjansson-dev libpam-dev unzip

      - name: Generate the artifacts
        run: |
          # Build pam_aad_oidc.so
          make

          # Build libnss
          wget https://github.com/hmeiland/linuxaad/archive/refs/tags/v0.3.1.zip
          unzip v0.3.1.zip
          cd linuxaad-0.3.1/libnss_aad/
          make
          mv .libs/libnss_aad.so.2.0 ../../libnss_aad.so

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.so'
